---
apiVersion: v1
kind: Namespace
metadata:
  name: default-ingress-backend
  labels:
    istio.io/rev: asm-1-17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: default-ingress-backend
spec:
  selector:
    matchLabels:
      app: default-ingress-backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: default-ingress-backend
    spec:
      containers:
      - name: ingress
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend-svc
  namespace: default-ingress-backend
  labels:
    version: "1.0"
spec:
  selector:
    app: default-ingress-backend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  default-bjdazure-tech-vs
  namespace: default-ingress-backend
spec:
  hosts:
  -  istio-default.bjdazure.tech
  gateways:
  -  aks-istio-ingress/default-bjdazure-tech-gw
  http:
  - route:
    - destination:
        host: default-backend-svc
        port:
          number: 80
