apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{ .Values.image.prodTag }}
  labels: 
    app: {{ .Values.image.name }}
    version: {{ .Values.image.prodVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        version: {{ .Values.service.prodVersion }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.prodTag }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{ .Values.image.stageTag }}
  labels: 
    app: {{ .Values.image.name }}
    version: {{ .Values.service.stageVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
        version: {{ .Values.service.stageVersion }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.stageTag }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
