#Reference - https://github.com/mosabami/aks-adv-workshop-yaml-files/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-api
spec:
  selector:
    matchLabels:
      app: ratings-api
  template:
    metadata:
      labels:
        app: ratings-api # the label for the pods and the deployments
        aadpodidbinding: "csi-to-key-vault"
    spec:
      containers:
      - name: ratings-api
        image: <acr name>.azurecr.io/ratings-api:v1 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        env:
          - name: MONGODB_URI # this is the variable our fruit smoothie web application is expecting
            valueFrom:
              secretKeyRef:
                name: key-vault-secret # this represents the secretName in the secret provider class 
                key: secret-content # name of secret that represents the data.key in the secret provider class
        volumeMounts:
        - name: keyvault
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 3000 # the application listens to this port
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 3000
            path: /healthz
        livenessProbe: # is the container healthy?
          httpGet:
            port: 3000
            path: /healthz
      volumes:
      - name: keyvault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: key-vault-secret-env

