apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.WORKLOAD_ID.NAME }}
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
    azure.workload.identity/tenant-id: {{ .Values.WORKLOAD_ID.TENANT_ID }}
  labels:
    azure.workload.identity/use: "true"