resources:
- repo: self

pool:
  name: Hosted Ubuntu 1604

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'BJD_APP02_Subscription'
    azureContainerRegistry: '{"loginServer":"bjd145.azurecr.io", "id" : "/subscriptions/<id>/resourceGroups/Core_Infra_ContainerRepo/providers/Microsoft.ContainerRegistry/registries/bjd145"}'
    dockerFile: Source/dockerfile
    imageName: golangrestapi
    additionalImageTags: '$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'BJD_APP02_Subscription'
    azureContainerRegistry: '{"loginServer":"bjd145.azurecr.io", "id" : "/subscriptions/<id>/resourceGroups/Core_Infra_ContainerRepo/providers/Microsoft.ContainerRegistry/registries/bjd145"}'
    action: 'Push an image'
    imageName: golangrestapi
    additionalImageTags: '$(Build.BuildId)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Kubernetes Artifacts'
  inputs:
    PathtoPublish: Deploy
    ArtifactName: yaml

- task: PublishBuildArtifacts@1
  displayName: 'Publish Helm Artifacts'
  inputs:
    PathtoPublish: Chart
    ArtifactName: goexamplechart